Load v4

In [1]:
import pandas as pd
master_v4 = pd.read_csv("/Users/satanhaha/Documents/MS ADS/ML 1/ML1 Final Project/Airbnb-Renting-Optimizer/data_processed/Chicago_Airbnb_Master_v4.csv")

master_v4.head()

,listing_id,price,accommodates,bedrooms,bathrooms,room_type,property_type,review_scores_rating,occupancy_proxy,weekend_occupancy_proxy,...,is_premium_transit_hub,shoreline_gravity,dist_to_nearest_beach_miles,crime_density_total,nb_homicides_half_mile,neigh_log_competition,neigh_price_index,price_vs_neigh_median,distance_to_downtown_km,neigh_avg_occ
0,2384,119.0,1,1.0,1.0,Private room,Private room in condo,4.99,0.046575,0.048077,...,0.3697,0.5992,0.5271,390.6212,0,4.488636,0.714765,1.117371,10.608606,0.441002
1,7126,89.0,2,1.0,1.0,Entire home/apt,Entire rental unit,4.73,0.172603,0.182692,...,0.0000,0.2589,2.9792,314.0505,0,6.496775,1.077181,0.554517,4.934691,0.342197
2,10945,203.0,4,2.0,1.0,Entire home/apt,Entire rental unit,4.74,0.109589,0.115385,...,0.7038,0.5976,0.8182,253.4784,0,5.533389,1.362416,1.000000,3.851522,0.328517
3,12140,339.0,3,1.0,1.0,Private room,Room in boutique hotel,4.95,0.572603,0.605769,...,0.7350,0.5051,1.4270,253.4784,0,5.533389,1.362416,1.669951,5.307615,0.328517
4,28749,258.0,6,3.0,2.0,Entire home/apt,Entire loft,4.83,0.797260,0.807692,...,0.7260,0.2820,2.8707,258.2845,0,6.013715,0.869128,1.992278,6.243387,0.422636

In [2]:
master_v4.shape

(7306, 71)

Merge with:
- nlp listing file (topics 0-7)
- nlp review file

In [3]:
# nlp listings
nlp_listings_0_7 = pd.read_csv("/Users/satanhaha/Documents/MS ADS/ML 1/ML1 Final Project/Airbnb-Renting-Optimizer/data_processed/listings_with_nlp_features.csv")
nlp_listings_0_7.drop(columns=['description','tokens_final'], inplace=True)
nlp_listings_0_7.rename(columns={'id': 'listing_id'}, inplace=True)

# nlp reviews
nlp_reviews = pd.read_csv("/Users/satanhaha/Documents/MS ADS/ML 1/ML1 Final Project/Airbnb-Renting-Optimizer/data_processed/Review Topics Final.csv")

In [4]:
master_v5 = master_v4.merge(
    nlp_listings_0_7,
    on="listing_id",
    how="left",
    validate="one_to_one"
)

master_v5 = master_v5.merge(
    nlp_reviews,
    on="listing_id",
    how="left",
    validate="one_to_one"
)

master_v5.head()

,listing_id,price,accommodates,bedrooms,bathrooms,room_type,property_type,review_scores_rating,occupancy_proxy,weekend_occupancy_proxy,...,topic_6,topic_7,location_quality,amenities_quality,parking,property_interior,sleep_comfort,overall_experience,accessibility,hotel_like_experience
0,2384,119.0,1,1.0,1.0,Private room,Private room in condo,4.99,0.046575,0.048077,...,0.051686,0.003908,0.777278,0.390296,0.358335,0.294125,0.408060,0.558576,0.228655,0.304287
1,7126,89.0,2,1.0,1.0,Entire home/apt,Entire rental unit,4.73,0.172603,0.182692,...,0.025036,0.386278,0.670910,0.582058,0.409550,0.349748,0.552666,0.600466,0.382934,0.262298
2,10945,203.0,4,2.0,1.0,Entire home/apt,Entire rental unit,4.74,0.109589,0.115385,...,0.005006,0.005005,0.863403,0.523719,0.434791,0.577407,0.141774,0.512716,0.161578,0.298800
3,12140,339.0,3,1.0,1.0,Private room,Room in boutique hotel,4.95,0.572603,0.605769,...,0.020880,0.347268,0.727978,1.000000,0.000000,0.478641,0.000000,0.268485,0.186604,0.220714
4,28749,258.0,6,3.0,2.0,Entire home/apt,Entire loft,4.83,0.797260,0.807692,...,0.618390,0.003692,0.750634,0.540407,0.526085,0.492242,0.779488,0.563332,0.177117,0.177489

In [5]:
master_v5.shape

(7306, 87)

In [6]:
master_v5.to_csv('Chicago_Airbnb_Master_v5.csv')